### ISSUE TITLE
Implement `ArrivalRetrieval` Class Using `dateparser` Library

### ISSUE THREAD

**Issue by ForYourEyesOnlyyy** [IU-Capstone-Project-2024/SayNoMore#14]
## Description

Implement the `ArrivalRetriever` class to extract and parse arrival dates from user inputs using the `dateparser` library. The implementation should align with the existing structure of the `DestinationRetriever` class.

## Tasks

1. **Review `DestinationRetriever` Class Structure**
   - Examine the existing `DestinationRetriever` class to understand its structure and methods.
   - Ensure that the `ArrivalRetriever` class follows a similar pattern.

2. **Set Up `ArrivalRetriever` Class**
   - Define the `ArrivalRetriever` class, maintaining consistency with the `DestinationRetriever` class signature.
   - Include initialization and any necessary class attributes.

3. **Integrate `dateparser` Library**
   - Use the `dateparser` library to handle and parse natural language date inputs.
   - Ensure the class can accurately interpret and convert various date formats into a standardized format.

4. **Implement Core Method(s)**
   - Develop the main method(s) to extract and return the arrival date from user input.
   - Ensure robust handling of different date expressions and edge cases.

5. **Testing**
   - Write unit tests to validate the functionality of the `ArrivalRetrieval` class.
   - Ensure the class correctly parses dates from diverse user inputs and formats.

## Acceptance Criteria

- The `ArrivalRetriever` class is implemented following the structure and signature of the `DestinationRetriever` class.
- The `dateparser` library is effectively integrated to parse arrival dates.
- The class accurately extracts and standardizes dates from user inputs.
- Comprehensive unit tests are provided and pass successfully.

## Additional Notes

- Refer to the `dateparser` [documentation](https://dateparser.readthedocs.io/en/latest/) for guidance on handling different date formats and natural language inputs.
- Ensure the class is well-documented to aid future maintenance and understanding.

**Comment by paket2004** [comment]
After evaluating the dateparser library for extracting and parsing arrival dates from user inputs, we encountered limitations in accurately handling the diverse and complex natural language date formats our users might provide. 

Given these challenges, we have decided to switch to using the VLLM (Very Large Language Model), which offers more robust capabilities for understanding and parsing natural language inputs. VLLM provides a more flexible and accurate approach for extracting dates from varied user expressions, aligning better with our project’s needs.

We will proceed with implementing the ArrivalRetriever class using VLLM instead of dateparser. This adjustment will enhance the reliability of our date extraction process and ensure a smoother user experience.
